version: '3.8'

services:
  webhook-handler:
    build:
      context: https://github.com/kc-rooted/webhooks-docker.git#main
      dockerfile: Dockerfile
    container_name: webhook-handler
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - MONDAY_API_TOKEN=${MONDAY_API_TOKEN}
      - MONDAY_WEBHOOK_SECRET=${MONDAY_WEBHOOK_SECRET:-}
      - AIRBYTE_WEBHOOK_TOKEN=${AIRBYTE_WEBHOOK_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
    networks:
      - webhook-network
    labels:
      # Traefik labels for automatic reverse proxy setup
      - "traefik.enable=true"
      - "traefik.http.routers.webhook-handler.rule=Host(`webhooks.yourdomain.com`)"
      - "traefik.http.routers.webhook-handler.entrypoints=websecure"
      - "traefik.http.routers.webhook-handler.tls.certresolver=letsencrypt"
      - "traefik.http.services.webhook-handler.loadbalancer.server.port=3000"

      # Health check labels
      - "webhook.health.check=/health"
      - "webhook.service=monday-airbyte-handler"

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  webhook-network:
    driver: bridge